export default {
inspire:{name:'Inspire',level:2,info:'Allies and yourself deal more damage, soldiers fight faster',image:'images/feats/level2/inspire.png'},
haymaker:{name:'Haymaker',level:2,info:'Passive | Punshes, kicks, and throws now deal damage', image:'images/feats/level2/haymaker.png'},
centurionsMarch:{name:'Centurion\'s',level:2,info:'Gain unlimited stamina for a short time',image:'images/feats/level2/centurionsMarch.png'},
inspire:{name:'Inspire',level:2,info:'Nearby allies deal more Damage, and soldiers fight faster.',image:'images/feats/level2/inspire.png'},
fiatLux:{name:'Fiat Lux',level:2,info:'Throw a flash grenade that blinds enemies for a few seconds.',image:'images/feats/level2/fiatLux.png'},
thickBlood:{name:'Thick Blood',level:2,info:'Passive | Gain immunity from regular bleed damage.',image:'images/feats/level2/thickBlood.png'},
righteousDeflection:{name:'Righteous Defelction',level:2,info:'Passive | Parry to gain high damage reduction for a short time',image:'images/feats/level2/righteousDeflection.png'},
revengeAttack:{name:'Revenge Attacks',level:2,info:'Passive | Attacks fill the revenge meter',image:'images/feats/level2/revengeAttack.png'},
juggernaut:{name:'Juggernaut',level:2,info:'Trade movement speed for better defense.',image:'images/feats/level2/juggernaut.png'},
shieldBasher:{name:'Shield Basher',level:2,info:'Passive | Shield based attacks now deal damage. (Shield bash which cannot be blocked or parried will now deal damage equivalent to light attack with default attack values on weapon)',image:'images/feats/level2/shieldBasher.png'},
thickSkin:{name:'Thick Skin',level:2,info:'Passive | Gain moderate Damage reduction. (Approx. 25% damage reduction)',image:'images/feats/level2/thickSkin.png'},
smokeBomb:{name:'Smoke Bomb',level:2,info:'Throw a smoke bomb on the ground that breaks the lock.',image:'images/feats/level2/smokeBomb.png'},
kunai:{name:'Kunai',level:2,info:'Throw a weighted dagger that does damage.',image:'images/feats/level2/kunai.png'},
chillingStare:{name:'Chilling Stare',level:2,info:'Nearby enemies have lower attack and defense.',image:'images/feats/level2/chillingStare.png'},
ironLungs:{name:'Iron Lungs',level:2,info:'Passive | You can still Sprint when Out of Stamina',image:'images/feats/level2/ironLungs.png'},
}
