export default {
inspire:{name:'Inspire',level:2,info:'Allies and yourself deal more damage, soldiers fight faster',image:'images/feats/level2/inspire.png'},
haymaker:{name:'Haymaker',level:2,info:'Passive | Punshes, kicks, and throws now deal damage', image:'images/feats/level2/haymaker.png'},
centurionsMarch:{name:'Centurion\'s',level:2,info:'Gain unlimited stamina for a short time',image:'images/feats/level2/centurionsMarch.png'},
fiatLux:{name:'Fiat Lux',level:2,info:'Throw a flash grenade that blinds enemies for a few seconds.',image:'images/feats/level2/fiatLux.png'},
thickBlood:{name:'Thick Blood',level:2,info:'Passive | Gain immunity from regular bleed damage.',image:'images/feats/level2/thickBlood.png'},
righteousDeflection:{name:'Righteous Defelction',level:2,info:'Passive | Parry to gain high damage reduction for a short time',image:'images/feats/level2/righteousDeflection.png'},
revengeAttack:{name:'Revenge Attacks',level:2,info:'Passive | Attacks fill the revenge meter',image:'images/feats/level2/revengeAttack.png'},
juggernaut:{name:'Juggernaut',level:2,info:'Trade movement speed for better defense.',image:'images/feats/level2/juggernaut.png'},
shieldBasher:{name:'Shield Basher',level:2,info:'Passive | Shield based attacks now deal damage. (Shield bash which cannot be blocked or parried will now deal damage equivalent to light attack with default attack values on weapon)',image:'images/feats/level2/shieldBasher.png'},
thickSkin:{name:'Thick Skin',level:2,info:'Passive | Gain moderate Damage reduction. (Approx. 25% damage reduction)',image:'images/feats/level2/thickSkin.png'},
smokeBomb:{name:'Smoke Bomb',level:2,info:'Throw a smoke bomb on the ground that breaks the lock.',image:'images/feats/level2/smokeBomb.png'},
kunai:{name:'Kunai',level:2,info:'Throw a weighted dagger that does damage.',image:'images/feats/level2/kunai.png'},
chillingStare:{name:'Chilling Stare',level:2,info:'Nearby enemies have lower attack and defense.',image:'images/feats/level2/chillingStare.png'},
rockSteady:{name:'Rock Steady',level:2,info:'Passive | You cannot be stumbled or unbalanced by Parries and Throws',image:'images/feats/level2/rockSteady.png'},
arrowStrike:{name:'Arrow Strike',level:2,info:'Call an arrow strike dealing moderate Damage over an area ',image:'images/feats/level2/arrowStrike.png'},
shootingStars:{name:'Shooting Stars',level:2,info:'Throw multiple shurikens in an area in front of you',image:'images/feats/level2/shootingStars.png'},
markedForDeath:{name:'Marked for Death',level:2,info:'Reveal target position and lower its attack and defense.',image:'images/feats/level2/markedForDeath.png'},
bearTrap:{name:'Bear Trap',level:2,info:'Medium damage trap that stops victims in their tracks.',image:'images/feats/level2/bearTrap.png'},
fleshWound:{name:'Flesh Wound',level:2,info:'Passive | Gain moderate Damage reduction.',image:'images/feats/level2/fleshWound.png'},
doomBanner:{name:'Doom Banner',level:2,info:'Nearby enemies have lower defense and attacks while within range.',image:'images/feats/level2/doomBanner.png'},
bloodLust:{name:'Blood Lust',level:2,info:'Passive | Killing heroes grants temporary attack and defense boosts',image:'images/feats/level2/bloodLust.png'},
winnersAdvantage:{name:'Winner\'s Advantage',level:2,info:'Passive | Gain a temporary buff after a successful attack.',image:'images/feats/level2/winnersAdvantage.png'},
}
