export default {
ironLungs:{name:'Iron Lungs',level:1,info:'Passive | You can still Sprint when Out of Stamina',image:'images/feats/level1/ironLungs.png'},
bodyCount:{name:'Body Count',level:1,info:'Passive | Killing soldier grants you health and stamina.', image:'images/feats/level1/bodyCount.png'},
rush:{name:'Rush',level:1,info:'Trigger to gain movement speed for a short duration',image:'images/feats/level1/rush.png'},
conqueror:{name:'Conqueror',level:1,info:'Passive | Capture and upgrade control zones faster.',image:'images/feats/level1/conqueror.png'},
comeAtMe:{name:'Come At Me',level:1,info:'Gain more Renown from kills, but take more Damage from Attacks.',image:'images/feats/level1/comeAtMe.png'},
harshJudgement:{name:'Harsh Judgement',level:1,info:'Reduce target\'s stamina for a short moment',image:'images/feats/level1/harshJudgement.png'},
bountyHunter:{name:'Bounty Hunter',level:1,info:'Passive | Gain Health & Stamina when you kill another hero',image:'images/feats/level1/bountyHunter.png'},
deadly:{name:'Deadly',level:1,info:'Passive | Attacks deal more Damage',image:'images/feats/level1/deadly.png'},
speedRevive:{name:'Speed Revive',level:1,info:'Passive | Rapidly revive fallen teammates.',image:'images/feats/level1/speedRevive.png'},
stealth:{name:'Stealth',level:1,info:'Passive | Hide yourself from the HUD, Radar & Aim Assist',image:'images/feats/level1/stealth.png'},
kiai:{name:'Kiai',level:1,info:'Stun nearby opponents with a scream',image:'images/feats/level1/kiai.png'},
fastRecovery:{name:'Fast Recovery',level:1,info:'Passive | Stamina regenerates faster.',image:'images/feats/level1/fastRecovery.png'},
throwFarther:{name:'Throw Farther',level:1,info:'Passive | Throw enemies farther',image:'images/feats/level1/throwFarther.png'},
tireless:{name:'Tireless',level:1,info:'Passive | Lose stamina at a lower rate.',image:'images/feats/level1/tireless.png'},
stunTrap:{name:'Stun Trap',level:1,info:'Trap that stuns enemies.',image:'images/feats/level1/stunTrap.png'},
}
