export default{
  aegis:{name:'Aegis',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  bastion:{name:'Bastion',info:'When in a zone or carrying a banner/offering gain 10% damage resistance',image:'images/perks/bastion.png'},
  bulkUp:{name:'Bulk Up',info:'When gaining a Renown level, increase maximum health by +4 (max 4 increases)',image:'images/perks/bulkUp.png'},
  cleverTactics:{name:'Clever Tactics',info:'Capture a zone and use banner/offerings 15% faster',image:'images/perks/cleverTactics.png'},
  crushThem:{name:'Crush Them',info:'Upon Hero Kill, your next attack deals 20% more damage',image:'images/perks/crushThem.png'},
  devourer:{name:'Devourer',info:'Upon execution, heal an additional +15 health',image:'images/perks/devourer.png'},
  earlyReaper:{name:'Early Reaper',info:'Upon spawn or when revived, first attack deals 20% more damage',image:'images/perks/earlyReaper.png'},
  endurance:{name:'Endurance',info:'When gaining a Renown level, receive 3% stamina cost reduction (max 4 gains)',image:'images/perks/endurance.png'},
  felineAgility:{name:'Feline Agility',info:'When gaining a Renown level, gain 4% movement speed for the first, then 2% for each subsequent level',image:'images/perks/felineAgility.png'},
  freshFocus:{name:'Fresh Focus',info:'When Out of Stamina, blocks and parries regenerate 20% stamina',image:'images/perks/freshFocus.png'},
  galestorm:{name:'Galestorm',info:'Upon Hero kill, gain 20% movement speed for 10 seconds',image:'images/perks/galestorm.png'},
  headHunter:{name:'Head Hunter',info:'For each unique player/bot Hero executed, increase max health by +4 (max 4 increases)',image:'images/perks/headHunter.png'},
  lastStand:{name:'Last Stand',info:'When in critical health,gain 20% damage resistance',image:'images/perks/lastStand.png'},
  radiantRebound:{name:'Radiant Rebound',info:'Upon spawn or when revived, gain 20% movement speed for 10 seconds',image:'images/perks/radiantRebound.png'},
  rapidRefresh:{name:'Rapid Refresh',info:'Upon takedown or when reviving an ally, Feats\' active cooldowns are reduced by 5%',image:'images/perks/rapidRefresh.png'},
  remedy:{name:'Remedy',info:'Upon Hero kill, heal +10 health',image:'images/perks/remedy.png'},
  risingDawn:{name:'Rising Dawn',info:'Revive allies to 75% health',image:'images/perks/risingDawn.png'},
  shieldsUp:{name:'Shields Up',info:'Upon spawn or when revived, receive a +15 health shield',image:'images/perks/shieldsUp.png'},
  supersonic:{name:'Supersonic',info:'In Revenge, gain 15% movement speed and uninterruptible sprint',image:'images/perks/supersonic.png'},
  survivalInstinct:{name:'Survival Instinct',info:'When in critical health, gain 15% stamina cost reduction',image:'images/perks/survivalInstinct.png'},
  vengefulBarrier:{name:'Vengeful Barrier',info:'When exiting Revenge, gain a +25 health shield',image:'images/perks/vengefulBarrier.png'},

}
