export default{
  aegis:{name:'Aegis',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  bastion:{name:'Bastion',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  bulkUp:{name:'Bulk Up',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  cleverTactics:{name:'Clever Tactics',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  crushThem:{name:'Crush Them',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  devourer:{name:'Devourer',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  earlyReaper:{name:'Early Reaper',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  endurance:{name:'Endurance',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  felineAgility:{name:'Feline Agility',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  freshFocus:{name:'Fresh Focus',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  galestorm:{name:'Galestorm',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  headHunter:{name:'Head Hunter',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  lastStand:{name:'Last Stand',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  radiantRebound:{name:'Radiant Rebound',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  rapidRefresh:{name:'Rapid Refresh',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  remedy:{name:'Remedy',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  risingDawn:{name:'Rising Dawn',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  shieldsUp:{name:'Shields Up',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  supersonic:{name:'Supersonic',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  survivalInstinct:{name:'Survival Instinct',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},
  vengefulBarrier:{name:'Vengeful Barrier',info:'All shields received are increaed by 20% ',image:'images/perks/aegis.png'},


}
