export default {
secondWind:{name:'Second Wind',level:3,info:'Recover some of your health.',image:'images/feats/level3/secondWind.png'},
pugio:{name:'Pugio',level:3,info:'A projectile that deals low damage and traps an enemy for a short time.', image:'images/feats/level3/pugio.png'},
sharpenBlade:{name:'Sharpen Blade',level:3,info:'Attacks inflict low Damage over time.',image:'images/feats/level3/sharpenBlade.png'},
pugnoMortis:{name:'Pugno Mortis',level:3,info:'Throw an explosive projectile dealing damage over an area.',image:'images/feats/level3/pugnoMortis.png'},
takedown:{name:'Takedown',level:3,info:'Throws make enemies fall to the ground.',image:'images/feats/level3/takedown.png'},
protectedRevive:{name:'Protected Revive',level:3,info:'Your revive is protected & grants allies health',image:'images/feats/level3/protectedRevive.png'},
neptunesWarth:{name:'Neptune\'s Wrath',level:3,info:'Throw a trident for moderate Damage',image:'images/feats/level3/neptunesWarth.png'},
boleadoras:{name:'Boleadoras',level:3,info:'Projectile that deals low damage and traps an enemy for a short time',image:'images/feats/level3/boleadoras.png'},
punchThrough:{name:'Punch Through',level:3,info:'Passive | Deal damage on blocked attacks. (Kind of a useless passive according to testing)',image:'images/feats/level3/punchThrough.png'},
healOnBlock:{name:'Heal on Block',level:3,info:'Passive | Blocking regenerates your health.',image:'images/feats/level3/healOnBlock.png'},
crossBow:{name:'Crossbow',level:3,info:'Fire a crossbow bolt for medium Damage.',image:'images/feats/level3/ironLungs.png'},
longBow:{name:'Long Bow',level:3,info:'Fire a long bow for moderate damage. (85 dmg)',image:'images/feats/level3/longBow.png'},
slipThrough:{name:'Slip Through',level:3,info:'Passive | Dodging raises Attack for a short duration',image:'images/feats/level3/slipThrough.png'},
steadFast:{name:'Steadfast',level:3,info:'Gain immunity from throw attempts for a short duration.',image:'images/feats/level3/steadFast.png'},
ironLungs:{name:'Iron Lungs',level:3,info:'Passive | You can still Sprint when Out of Stamina',image:'images/feats/level3/ironLungs.png'},
}
