export default {
secondWind:{name:'Second Wind',level:3,info:'Recover some of your health.',image:'images/feats/level3/secondWind.png'},
pugio:{name:'Pugio',level:3,info:'A projectile that deals low damage and traps an enemy for a short time.', image:'images/feats/level3/pugio.png'},
sharpenBlade:{name:'Sharpen Blade',level:3,info:'Attacks inflict low Damage over time.',image:'images/feats/level3/sharpenBlade.png'},
pugnoMortis:{name:'Pugno Mortis',level:3,info:'Throw an explosive projectile dealing damage over an area.',image:'images/feats/level3/pugnoMortis.png'},
takedown:{name:'Takedown',level:3,info:'Throws make enemies fall to the ground.',image:'images/feats/level3/takedown.png'},
protectedRevive:{name:'Protected Revive',level:3,info:'Your revive is protected & grants allies health',image:'images/feats/level3/protectedRevive.png'},
neptunesWrath:{name:'Neptune\'s Wrath',level:3,info:'Throw a trident for moderate Damage',image:'images/feats/level3/neptunesWrath.png'},
boleadoras:{name:'Boleadoras',level:3,info:'Projectile that deals low damage and traps an enemy for a short time',image:'images/feats/level3/boleadoras.png'},
punchThrough:{name:'Punch Through',level:3,info:'Passive | Deal damage on blocked attacks. (Kind of a useless passive according to testing)',image:'images/feats/level3/punchThrough.png'},
healOnBlock:{name:'Heal on Block',level:3,info:'Passive | Blocking regenerates your health.',image:'images/feats/level3/healOnBlock.png'},
crossBow:{name:'Crossbow',level:3,info:'Fire a crossbow bolt for medium Damage.',image:'images/feats/level3/crossBow.png'},
longBow:{name:'Long Bow',level:3,info:'Fire a long bow for moderate damage. (85 dmg)',image:'images/feats/level3/longBow.png'},
slipThrough:{name:'Slip Through',level:3,info:'Passive | Dodging raises Attack for a short duration',image:'images/feats/level3/slipThrough.png'},
steadFast:{name:'Steadfast',level:3,info:'Gain immunity from throw attempts for a short duration.',image:'images/feats/level3/steadFast.png'},
hardToKill:{name:'Hard to Kill',level:3,info:'Passive | Losing Health increases your Damage reduction',image:'images/feats/level3/hardToKill.png'},
nukekubi:{name:'Nukekubi',level:3,info:'Gain Stamina on successful attacks',image:'images/feats/level3/nukekubi.png'},
fury:{name:'Fury',level:3,info:'Raise sprint speed slightly and attack and defense greatly.',image:'images/feats/level3/fury.png'},
battleCry:{name:'Battle Cry',level:3,info:'Increase ally Damage and makes enemy soldiers flee.',image:'images/feats/level3/battleCry.png'},
toughAsNails:{name:'Tough as Nails',level:3,info:'Passive | Raises max Health when unlocked.',image:'images/feats/level3/toughAsNails.png'},
throwingAxe:{name:'ThrowingAxe',level:3,info:'Throw an axe that deals medium damage.',image:'images/feats/level3/throwingAxe.png'},
javelin:{name:'Javelin',level:3,info:'Throw a javelin for moderate damage.',image:'images/feats/level3/javelin.png'},
}
