export default {
catapult:{name:'Catapult',level:4,info:'Call a catapult strike over an area.',image:'images/feats/level4/catapult.png'},
stalwartBanner:{name:'Stalwart Banner',level:4,info:'Nearby allies continuously regain health.', image:'images/feats/level4/stalwartBanner.png'},
phalanx:{name:'Phalanx',level:4,info:'Grand a shield to all alive teammates (yourself included)',image:'images/feats/level4/phalanx.png'},
moraleBooster:{name:'Morale Booster',level:4,info:'Improve the attacks of nearby allies for a short duration.',image:'images/feats/level4/moraleBooster.png'},
igneusImber:{name:'Igneus Imber',level:4,info:'Several grenades that deal moderate damage over an area',image:'images/feats/level4/igneusImber.png'},
regenerate:{name:'Regenerate',level:4,info:'Passive | Regenerates your health when out of combat.',image:'images/feats/level4/regenerate.png'},
fearItself:{name:'Fear Itself',level:4,info:'Enemies around you have lower Stamina regeneration and defenses',image:'images/feats/level4/fearItself.png'},
roarOfTheCrowd:{name:'Roar Of The Crowd',level:4,info:'Greatly raise attack and sprint stats',image:'images/feats/level4/roarOfTheCrowd.png'},
dauntless:{name:'Dauntless',level:4,info:'Your actions can\'t be interrupted for a short duration.',image:'images/feats/level4/dauntless.png'},
lastLaugh:{name:'Last Laugh',level:4,info:'Passive | Drop a high Damage grenade when you die.',image:'images/feats/level4/lastLaugh.png'},
nailBomb:{name:'Nail Bomb',level:4,info:'A trap dealing Bleed Damage in an area of effect',image:'images/feats/level4/nailBomb.png'},
arrowStorm:{name:'Arrow Storm',level:4,info:'Aerial attack that deals medium damage in multiple areas.',image:'images/feats/level4/arrowStorm.png'},
unblockable:{name:'Unbl',level:4,info:'Your attacks can not be blocked for a short duration',image:'images/feats/level4/unblockable.png'},
staggeringBlow:{name:'Staggering Blow',level:4,info:'Heavy Attacks cause enemies to fall',image:'images/feats/level4/staggeringBlow.png'},
fireTrap:{name:'Fire Trap',level:4,info:'A trap that explodes and creates a fire area of effect',image:'images/feats/level4/fireTrap.png'},
yamaUba:{name:'Yama Uba',level:4,info:'Gain Health on successful attacks',image:'images/feats/level4/yamaUba.png'},
fireFlask:{name:'Fire Flask',level:4,info:'Throw a projectile creating a fire area of effect.',image:'images/feats/level4/fireFlask.png'},
slippery:{name:'Slippery',level:4,info:'Activate to auto block grab attempts for a duration.',image:'images/feats/level4/slippery.png'},
autoRevive:{name:'Auto Revive',level:4,info:'Passive | When dying, revive without the help of another player.',image:'images/feats/level4/autoRevive.png'},
berserker:{name:'Berserker',level:4,info:'Significantly raise your speed, attack and defense.',image:'images/feats/level4/berserker.png'},
scout:{name:'Scout',level:4,info:'All enemies are marked for death and show up on radar.',image:'images/feats/level4/scout.png'},
spearStorm:{name:'Spear Storm',level:4,info:'Aerial Attack that deals medium Damage in multiple areas',image:'images/feats/level4/spearStorm.png'},
championsAura:{name:'Champio\'s Aura',level:4,info:'Gain an aura which heals you and nearby allies',image:'images/feats/level4/championsAura.png'},
}
