export default {
catapult:{name:'Catapult',level:4,info:'Call a catapult strike over an area.',image:'images/feats/level4/catapult.png'},
stalwartBanner:{name:'Stalwart Banner',level:4,info:'Nearby allies continuously regain health.', image:'images/feats/level4/stalwartBanner.png'},
phalanx:{name:'Phalanx',level:4,info:'Grand a shield to all alive teammates (yourself included)',image:'images/feats/level4/phalanx.png'},
moraleBooster:{name:'Morale Booster',level:4,info:'Improve the attacks of nearby allies for a short duration.',image:'images/feats/level4/moraleBooster.png'},
igneusImber:{name:'Igneus Imber',level:4,info:'Several grenades that deal moderate damage over an area',image:'images/feats/level4/igneusImber.png'},
regenerate:{name:'Regenerate',level:4,info:'Passive | Regenerates your health when out of combat.',image:'images/feats/level4/regenerate.png'},
fearItself:{name:'Fear Itself',level:4,info:'Enemies around you have lower Stamina regeneration and defenses',image:'images/feats/level4/fearItself.png'},
roarOfTheCrowd:{name:'Roar Of The Crowd',level:4,info:'Greatly raise attack and sprint stats',image:'images/feats/level4/roarOfTheCrowd.png'},
dauntless:{name:'Dauntless',level:4,info:'Your actions can\'t be interrupted for a short duration.',image:'images/feats/level4/dauntless.png'},
lastLaugh:{name:'Last Laugh',level:4,info:'Passive | Drop a high Damage grenade when you die.',image:'images/feats/level4/lastLaugh.png'},
nailBomb:{name:'Nail Bomb',level:4,info:'A trap dealing Bleed Damage in an area of effect',image:'images/feats/level4/nailBomb.png'},
arrowStorm:{name:'Arrow Storm',level:4,info:'Aerial attack that deals medium damage in multiple areas.',image:'images/feats/level4/arrowStorm.png'},
unblockable:{name:'Unbl',level:4,info:'Passive | You can still Sprint when Out of Stamina',image:'images/feats/level4/ironLungs.png'},
ironLungs:{name:'Unblockable',level:4,info:'Your attacks can not be blocked for a short duration.',image:'images/feats/level4/unblockable.png'},
ironLungs:{name:'Iron Lungs',level:4,info:'Passive | You can still Sprint when Out of Stamina',image:'images/feats/level4/ironLungs.png'},
}
